name: Get ECR Image Digest 2

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo Name:'
        default: 'nginx-app-repo'
        required: true
      tag:
        description: 'Select Tag:'
        required: true
        type: choice
        options: ${{ fromJSON(needs.get-tags.outputs.tags) }}

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.list-tags.outputs.tag-list }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Fetch Image Tags from ECR
        id: list-tags
        run: |
          REPO_NAME="nginx-app-repo"  # Modify as needed

          TAGS=$(aws ecr list-images --repository-name "$REPO_NAME" \
            --query "imageIds[*].imageTag" --output json)

          echo "tag-list=$TAGS" >> $GITHUB_OUTPUT

  get-image-digest:
    runs-on: ubuntu-latest
    needs: get-tags
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Get Image Digest from ECR
        run: |
          REPO_NAME="${{ github.event.inputs.repo }}"
          IMAGE_TAG="${{ github.event.inputs.tag }}"

          IMAGE_DIGEST=$(aws ecr describe-images \
            --repository-name "$REPO_NAME" \
            --image-ids imageTag="$IMAGE_TAG" \
            --query "imageDetails[0].imageDigest" \
            --output text)

          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV

      - name: Use Image Digest in Another Step
        run: echo "The image digest is $IMAGE_DIGEST"
