name: test

on: 
    workflow_dispatch

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
      - run: |
            gh variable list
            gh variable set TEST_VAR --body "Set from workflow"
            gh variable list
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
