name: Get ECR Image Digest

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo Name:'
        default: 'nginx-app-repo'
        required: true
      tag:
        description: 'Enter Tag (See Logs for Available Tags):'
        required: true
        default: 'latest'

jobs:
  list-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Fetch Available Image Tags from ECR
        run: |
          REPO_NAME="${{ github.event.inputs.repo }}"
          echo "Fetching tags for repository: $REPO_NAME"

          TAGS=$(aws ecr list-images --repository-name "$REPO_NAME" \
            --query "imageIds[*].imageTag" --output json)

          echo "Available tags:"
          echo "$TAGS"

  get-image-digest:
    runs-on: ubuntu-latest
    needs: list-tags
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Get Image Digest from ECR
        run: |
          REPO_NAME="${{ github.event.inputs.repo }}"
          IMAGE_TAG="${{ github.event.inputs.tag }}"

          IMAGE_DIGEST=$(aws ecr describe-images \
            --repository-name "$REPO_NAME" \
            --image-ids imageTag="$IMAGE_TAG" \
            --query "imageDetails[0].imageDigest" \
            --output text)

          echo "Selected Tag: $IMAGE_TAG"
          echo "Image Digest: $IMAGE_DIGEST"
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV

      - name: Use Image Digest in Another Step
        run: echo "The image digest is $IMAGE_DIGEST"
