# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Extract PR number
      if: github.event_name == 'pull_request'
      run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
    
    # Step 1: Check if SEQ_NUMBER exists, else initialize it
    - name: Retrieve or Initialize Sequence Number
      run: |
        EXISTING_SEQ=$(gh variable list --json name | jq -r '.[] | select(.name=="SEQ_NUMBER") | .name')
        if [ -z "$EXISTING_SEQ" ]; then
          echo "SEQ_NUMBER=100" >> $GITHUB_ENV
          gh variable set SEQ_NUMBER --body "100"
        else
          echo "SEQ_NUMBER=$(gh variable get SEQ_NUMBER)" >> $GITHUB_ENV
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 2: Increment SEQ_NUMBER
    - name: Increment Sequence Number
      run: |
        NEW_SEQ=$(( $SEQ_NUMBER + 1 ))
        echo "NEW_SEQ=$NEW_SEQ" >> $GITHUB_ENV
        gh variable set SEQ_NUMBER --body "$NEW_SEQ"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          nichocha/belajar-cicd:latest
          nichocha/belajar-cicd:pr-${{ env.PR_NUMBER }}
          nichocha/belajar-cicd:seq-${{ env.NEW_SEQ }}
