name: 020-manual-input-workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
      greeting:
        description: 'Choose a greeting'
        required: true
        default: 'Hello'
        type: choice
        options:
          - Hello
          - Hi
          - Hey
          - Greetings

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }}"
